const fs = require("fs");
const path = require("path");

const png = fs.readFileSync(path.join(__dirname, "icon.png"));
const header = Buffer.alloc(6);
header.writeUInt16LE(0, 0);
header.writeUInt16LE(1, 2);
header.writeUInt16LE(1, 4);
const entry = Buffer.alloc(16);
entry[0] = 0;
entry[1] = 0;
entry[2] = 0;
entry[3] = 0;
entry.writeUInt16LE(1, 4);
entry.writeUInt16LE(32, 6);
entry.writeUInt32LE(png.length, 8);
entry.writeUInt32LE(22, 12);
const ico = path.join(__dirname, "icon.ico");
fs.writeFileSync(ico, Buffer.concat([header, entry, png]));
console.log("icon.ico ready", fs.statSync(ico).size);
